### ISSUE TITLE
Rename to `@jupyterlite/ai`?

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlab-codestral#11]
After https://github.com/jupyterlite/jupyterlab-codestral/pull/10 and https://github.com/jupyterlite/jupyterlab-codestral/issues/5, this extension will be able to support more providers than just MistralAI, based on what `langchain.js` provides.

So it will make sense to rename it to something more generic. An idea could be `@jupyterlite/ai`, since the repo currently lives in the `jupyterlite` GitHub organization. Even though it could be used with a regular JupyterLab too.

Other ideas welcome!

**Comment by brichet** [comment]
`@jupyterlite/ai` is a good option.

I was also thinking of `@jupyter/langchainjs` to be more explicit, but that would restrict possible future change of providers.

**Comment by jtpio** [comment]
Right, I think the reasoning for `@jupyterlite/ai` was to have something like Jupyter AI using langchain Python, but in the browser using langchain.js.

Maybe having a more general name would also let us do more things that may fall outside the scope of the langchain framework.
